### ISSUE TITLE
Add -cluster to script CLI command

### ISSUE THREAD

**Issue by brownc** [sapia-oss/corus#25]
Currently the "script" CLI command doesn't support a -cluster (unless it's not documented in the man page :))

So, where we have a "deploy.txt" for deploying a cluster, and a "deploy-single.txt" we can't use the "set-ports" and "set-params" files for BOTH of these, as by default all the individual commands in the set-* scripts have -cluster on the end.

To support deploy.txt and deploy-single.txt you therefore must maintain two lots of set-* scripts, which is sub-optimal to quote a wise man I know...

If we add a "-cluster" option to the script command, we can then remove said flag from inside all our set-* scripts, and maintain just one copy of the files.  the main deploy[-single].txt would then be responsible for setting locally or cluster-wide.

Can we squeeze into 7.1 please - as we're seeing more and more need to deploy single vs cluster (testing, EOS, etc).

Thanks!

**Comment by yduchesne** [comment]
You got it, asap

**Comment by yduchesne** [comment]
Fixed in 4.7.1. Can I open a beer at relax on the couch now ? ;)

Details:
Invoking a script with "script <path_to_script> -cluster" will have the effect of activating clustering for all commands in the script that support the -cluster option (even -cluster is not specified for these commands in the script itself). So handle with care ;)
